---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - base

- hosts: docker-registry:children
  become: true
  become_user: root
  become_method: sudo
  roles:
    - webserver
    - docker
    - docker-registry
